# Created using wingetcreate 1.5.2.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: NotroDev.SkEditor+
PackageVersion: 1.7.8
InstallerType: msi
ProductCode: '{29E3F9DC-A3F3-499B-A230-3C9F02903C82}'
Dependencies:
  PackageDependencies:
    - PackageIdentifier: Microsoft.DotNet.DesktopRuntime.6
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/NotroDev/SkEditorPlus/releases/download/v1.7.8/SkEditorPlus-Installer.msi
  InstallerSha256: 7E7AF499E49548939487D50594FF3CE0325FDF570FA3618252155C615A604AA3
ManifestType: installer
ManifestVersion: 1.5.0
